### PR TITLE
Completed Python 3 compatibility

### PR DESCRIPTION
**Pull request by claudep**
Hi Piotr,
I've worked today on translitcodec Python 3 compatiblity. I'm proposing this work as a pull request if you are interested to maintain the code in your repository (and contact the original author for Pypi publication).
Are you OK with that?

### CODE REVIEW

**Comment by claudep** [comment]
I just realized that Jason (original author) has a Github account. 
@jek, are you interested to continue maintaining this package?

**Comment by claudep** [comment]
And now I see there is already a bitbucket repo (https://bitbucket.org/jek/translitcodec). Sorry, Google wasn't my friend :-P

**Comment by jek** [comment]
Happy to see activity on this project- I'd be delighted to pass on maintainership.

**Comment by claudep** [comment]
@jellonek Any input? Interested to maintain it?

**Comment by claudep** [comment]
No answer, so assuming "No". I have recreated a new Github repo based on the Bitbucket one (https://github.com/claudep/translitcodec).

**Comment by jek** [comment]
FYI I have redirected the bitbucket repo to claudep/translitcodec.

Should anything be needed from its original home during transition, it's
available at https://bitbucket.org/jek/translitcodec-old

**Comment by claudep** [comment]
Great, thanks.

**Comment by jellonek** [comment]
Sorry for late answer - great to know that this code still lives. I'll also redirect to this address.

**Pull request closed without merging**
